
import type { YogaPose } from './types';

export const ALL_POSES: YogaPose[] = [
  // --- Standing Poses (선 자세) ---
  {
    name: '산 자세 (타다아사나)',
    sanskritName: 'Tadasana',
    description: '모든 선 자세의 기초가 되는 동작입니다. 바른 자세를 만들고 발바닥으로 땅을 단단히 지지하며 척추를 길게 늘려줍니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 4v16m-2 0h4m-6-6l2-3m4 3l-2-3"/></svg>`,
    benefits: ["자세 교정 및 균형 감각 향상", "허벅지, 무릎, 발목 강화", "복부와 엉덩이 탄력 증가"],
    contraindications: ["두통", "불면증", "저혈압"],
    difficulty: 'Beginner',
  },
  {
    name: '의자 자세 (우트카타아사나)',
    sanskritName: 'Utkatasana',
    description: '허벅지와 발목을 강화하고 어깨, 엉덩이, 등의 근육을 단련하는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 21l3-8 3-4h-2m4 12l-3-8-3-4h2m-6 0l2-5h6l2 5"/></svg>`,
    benefits: ["발목, 허벅지, 종아리, 척추 강화", "어깨와 가슴 스트레칭", "복부 장기 자극"],
    contraindications: ["두통", "불면증", "저혈압"],
    difficulty: 'Beginner',
  },
  {
    name: '독수리 자세 (가루다아사나)',
    sanskritName: 'Garudasana',
    description: '집중력과 근력이 필요한 균형 동작으로, 어깨와 등 상부를 시원하게 열어줍니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21v-8m-2 3c0-2 4-2 4-5s-4-4-4-4-4 1-4 4"/></svg>`,
    benefits: ["팔과 다리 근력 강화", "균형 감각 및 집중력 향상", "등 상부와 어깨 스트레칭"],
    contraindications: ["무릎 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '전사 자세 I (비라바드라아사나 I)',
    sanskritName: 'Virabhadrasana I',
    description: '가슴과 폐, 어깨와 목, 복부, 서혜부(장요근)를 스트레칭하는 힘찬 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20l-3 3H5v-3l3-3m4-4l-3 3m11-1l-3 3M8 4l8 8"/></svg>`,
    benefits: ["어깨, 팔, 다리, 발목, 등 강화", "골반, 가슴, 폐 개방", "집중력, 균형감각, 안정성 향상"],
    contraindications: ["고혈압", "심장 질환"],
    difficulty: 'Beginner',
  },
  {
    name: '전사 자세 II (비라바드라아사나 II)',
    sanskritName: 'Virabhadrasana II',
    description: '다리와 발목을 강화하고 서혜부, 가슴, 어깨를 시원하게 열어주는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 4v16m-8-8h16M6 9l-2 3 2 3m12-6l2 3-2 3"/></svg>`,
    benefits: ["다리와 발목 강화 및 스트레칭", "서혜부, 가슴, 폐, 어깨 스트레칭", "복부 장기 자극"],
    contraindications: ["설사", "고혈압", "목 통증"],
    difficulty: 'Beginner',
  },
  {
    name: '전사 자세 III (비라바드라아사나 III)',
    sanskritName: 'Virabhadrasana III',
    description: '한 다리로 서서 균형을 잡으며 다리와 발목을 강화하고 자세를 교정하는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16.47,14.5l-4.24-4.24a2,2,0,0,0-2.83,0L5.2,14.5m10-10L17,6.2m-5.83-1L9.4,3.42M14,19.25a2.25,2.25,0,0,1-4.5,0V16h4.5Z"/></svg>`,
    benefits: ["다리와 발목 강화", "균형 감각 및 집중력 향상", "복부 탄력 증가"],
    contraindications: ["고혈압", "심장 질환", "최근의 엉덩이/무릎 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '삼각 자세 (트리코나아사나)',
    sanskritName: 'Trikonasana',
    description: '다리, 서혜부, 햄스트링, 엉덩이를 스트레칭하고 가슴과 어깨를 열어주는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3L2 21h20L12 3zm0 4v10m-4-2h8"/></svg>`,
    benefits: ["허벅지, 무릎, 발목 강화", "엉덩이, 서혜부, 햄스트링, 종아리 스트레칭", "가슴과 어깨 개방"],
    contraindications: ["설사", "두통", "저혈압"],
    difficulty: 'Beginner',
  },
  {
    name: '측각도 자세 (우티타 파르스바코나아사나)',
    sanskritName: 'Utthita Parsvakonasana',
    description: '다리를 강화하면서 서혜부, 척추, 허리, 어깨를 스트레칭하는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 21l6-9 6 9M6 12l12-8"/></svg>`,
    benefits: ["다리, 무릎, 발목 강화", "서혜부, 척추, 허리, 가슴, 폐 스트레칭", "복부 장기 자극"],
    contraindications: ["두통", "고혈압/저혈압", "불면증"],
    difficulty: 'Beginner',
  },
  {
    name: '나무 자세 (브릭샤아사나)',
    sanskritName: 'Vrikshasana',
    description: '나무처럼 뿌리를 내리고 곧게 서서 균형 감각을 키우는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21v-6m-3 3-6-6 6-6 3 3 3-3 6 6-6 6-3-3z"/></svg>`,
    benefits: ["균형 감각 및 안정성 향상", "다리와 코어 강화", "마음의 평온과 집중력 증진"],
    contraindications: ["두통", "불면증", "저혈압"],
    difficulty: 'Beginner',
  },
  {
    name: '선 활 자세 (나타라자아사나)',
    sanskritName: 'Natarajasana',
    description: '춤의 신 시바를 형상화한 우아한 후굴 및 균형 동작으로, 집중력을 요합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21a9 9 0 0 1-9-9c0-3.87 2.39-7.17 5.76-8.55L12 3l3.24.45A9 9 0 0 1 12 21z"/><path d="M12 7v4l3 3"/></svg>`,
    benefits: ["균형 감각 향상", "어깨, 가슴, 허벅지, 서혜부, 복부 스트레칭", "다리와 발목 강화"],
    contraindications: ["저혈압", "심각한 허리 또는 무릎 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '반달 자세 (아르다 찬드라아사나)',
    sanskritName: 'Ardha Chandrasana',
    description: '한 다리로 서서 몸을 반달 모양으로 만들며 다리와 발목을 강화하고 햄스트링을 늘려줍니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zM3 12h18"/></svg>`,
    benefits: ["복부, 발목, 허벅지, 엉덩이, 척추 강화", "서혜부, 햄스트링, 종아리 스트레칭", "협응력 및 균형 감각 향상"],
    contraindications: ["두통", "저혈압", "설사"],
    difficulty: 'Intermediate',
  },
  
  // --- Floor / Seated Poses (바닥 / 앉은 자세) ---
  {
    name: '견상 자세 (다운독 / 아도 무카 스바나아사나)',
    sanskritName: 'Adho Mukha Svanasana',
    description: '전신을 깨우고 활력을 주는 필수적인 휴식 겸 강화 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>`,
    benefits: ["햄스트링과 종아리 스트레칭", "전신 활력 증진", "팔과 다리 강화"],
    contraindications: ["고혈압", "임신 후기", "손목터널증후군"],
    difficulty: 'Beginner',
  },
  {
    name: '아기 자세 (발라아사나)',
    sanskritName: 'Balasana',
    description: '뇌를 진정시키고 스트레스와 피로를 풀어주는 편안한 휴식 자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2c-3.31 0-6 2.69-6 6 0 2.28 1.28 4.25 3.14 5.24L12 22l2.86-8.76A5.99 5.99 0 0018 8c0-3.31-2.69-6-6-6zM9 12h6"/></svg>`,
    benefits: ["마음의 안정", "스트레스 및 피로 해소", "골반과 등 스트레칭"],
    contraindications: ["설사", "무릎 부상", "임신"],
    difficulty: 'Beginner',
  },
  {
    name: '소-고양이 자세 (마르자리아사나-비틸라아사나)',
    sanskritName: 'Marjaryasana-Bitilasana',
    description: '척추의 유연성을 높이고 몸의 긴장을 풀어주는 웜업 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 14c-2 0-3 3-3 3s1 3 3 3 5-3 5-3 1 3 3 3 3-3 3-3M4 8s2-2 4-2 4 2 4 2 2-2 4-2 4 2 4 2"/></svg>`,
    benefits: ["자세 교정 및 균형", "척추와 목 강화 및 스트레칭", "복부 장기 마사지"],
    contraindications: ["목 부상"],
    difficulty: 'Beginner',
  },
  {
    name: '코브라 자세 (부장가아사나)',
    sanskritName: 'Bhujangasana',
    description: '어깨, 가슴, 복부 근육을 스트레칭하는 후굴 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 14c4 0 8-4 8-9S16 2 12 2 4 5 4 5s4 9 8 9z"/><path d="M12 14v10"/></svg>`,
    benefits: ["척추 강화", "가슴, 폐, 어깨, 복부 스트레칭", "엉덩이 탄력 증가"],
    contraindications: ["허리 부상", "손목터널증후군", "두통", "임신"],
    difficulty: 'Beginner',
  },
  {
    name: '업독 자세 (우르드바 무카 스바나아사나)',
    sanskritName: 'Urdhva Mukha Svanasana',
    description: '상체를 깨우고 가슴을 활짝 여는 강력한 후굴 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 14c0 4 4 8 8 8s8-4 8-8-4-10-8-10-8 6-8 10z"/><path d="M12 4v6"/></svg>`,
    benefits: ["자세 교정", "척추, 팔, 손목 강화", "가슴, 폐, 어깨, 복부 스트레칭"],
    contraindications: ["허리 부상", "손목터널증후군", "임신"],
    difficulty: 'Intermediate',
  },
  {
    name: '막대 자세 (단다아사나)',
    sanskritName: 'Dandasana',
    description: '앉은 자세의 기본으로, 척추를 바르게 세우고 등 근육을 강화합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 4v16m-4 0h8m-8-8h8"/></svg>`,
    benefits: ["등 근육 강화", "어깨와 가슴 스트레칭", "자세 교정"],
    contraindications: ["손목 또는 허리 부상"],
    difficulty: 'Beginner',
  },
  {
    name: '앉은 전굴 자세 (파스치모타나아사나)',
    sanskritName: 'Paschimottanasana',
    description: '척추, 어깨, 햄스트링을 깊게 스트레칭하는 앉아서 굽히는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>`,
    benefits: ["뇌 진정", "척추와 어깨 스트레칭", "간, 신장, 자궁 기능 자극"],
    contraindications: ["천식", "설사", "허리 부상"],
    difficulty: 'Beginner',
  },
  {
    name: '나비 자세 (바다 코나아사나)',
    sanskritName: 'Baddha Konasana',
    description: '골반과 서혜부를 유연하게 만들어주는 앉은 자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"/><path d="M12 12l-4 4"/><path d="M12 12l4 4"/></svg>`,
    benefits: ["복부 장기 자극", "허벅지 안쪽, 서혜부, 무릎 스트레칭", "생리통 완화"],
    contraindications: ["서혜부 또는 무릎 부상"],
    difficulty: 'Beginner',
  },
  {
    name: '소머리 자세 (고무카아사나)',
    sanskritName: 'Gomukhasana',
    description: '엉덩이, 발목, 허벅지, 어깨, 가슴 등을 골고루 스트레칭하는 앉은 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M8 12h8"/></svg>`,
    benefits: ["발목, 엉덩이, 허벅지 스트레칭", "가슴과 어깨 개방", "광배근 신장"],
    contraindications: ["심각한 목 또는 어깨 문제"],
    difficulty: 'Intermediate',
  },
  {
    name: '연꽃 자세 (파드마아사나)',
    sanskritName: 'Padmasana',
    description: '명상을 위한 최고의 자세로, 골반의 개방과 발목의 유연성이 필요합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    benefits: ["뇌 진정", "골반, 척추, 복부, 방광 자극", "발목과 무릎 스트레칭"],
    contraindications: ["발목 부상", "무릎 부상"],
    difficulty: 'Advanced',
  },
  {
    name: '보트 자세 (나바아사나)',
    sanskritName: 'Navasana',
    description: '코어를 강화하고 균형 감각과 안정성을 시험하는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12h20L12 22 2 12z"/></svg>`,
    benefits: ["복부, 고관절 굴곡근, 척추 강화", "신장, 갑상선, 전립선 자극", "스트레스 해소"],
    contraindications: ["천식", "설사", "두통", "심장 질환"],
    difficulty: 'Intermediate',
  },
  
  // --- Backbends (후굴) ---
  {
    name: '브릿지 자세 (세투 반다 사르방가아사나)',
    sanskritName: 'Setu Bandha Sarvangasana',
    description: '가슴을 열고 목과 척추를 스트레칭하는 누운 후굴 자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12a10 10 0 0110-10 10 10 0 0110 10M4 22h16"/></svg>`,
    benefits: ["가슴, 목, 척추 스트레칭", "뇌 진정 및 스트레스 완화", "복부 장기 자극"],
    contraindications: ["목 부상"],
    difficulty: 'Beginner',
  },
  {
    name: '바퀴 자세 (우르드바 다누라아사나)',
    sanskritName: 'Urdhva Dhanurasana',
    description: '가슴을 열고 팔다리를 강화하며 전신에 에너지를 불어넣는 고급 후굴 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20c4.42 0 8-3.58 8-8s-3.58-8-8-8-8 3.58-8 8 3.58 8 8 8z"/></svg>`,
    benefits: ["가슴과 폐 스트레칭", "팔, 손목, 다리, 엉덩이, 복부, 척추 강화", "에너지 증진"],
    contraindications: ["손목터널증후군", "심장 질환", "두통"],
    difficulty: 'Advanced',
  },
  {
    name: '낙타 자세 (우스트라아사나)',
    sanskritName: 'Ustrasana',
    description: '무릎을 꿇고 상체를 뒤로 젖혀 몸의 앞면 전체를 여는 깊은 후굴 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8 14s1.5 2 4 2 4-2 4-2"/><path d="M9 9h6"/></svg>`,
    benefits: ["몸의 전면부 전체 스트레칭", "등 근육 강화", "복부와 목의 기관 자극"],
    contraindications: ["고혈압/저혈압", "편두통", "불면증"],
    difficulty: 'Intermediate',
  },
  {
    name: '활 자세 (다누라아사나)',
    sanskritName: 'Dhanurasana',
    description: '엎드려서 손으로 발목을 잡고 당겨 몸을 활처럼 만드는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21c-4.97 0-9-4.03-9-9s4.03-9 9-9 9 4.03 9 9-4.03 9-9 9z"/><path d="M7 10l5 5 5-5"/></svg>`,
    benefits: ["몸의 전면부 스트레칭", "등 근육 강화", "복부 장기 자극"],
    contraindications: ["고혈압/저혈압", "편두통", "불면증", "허리 부상"],
    difficulty: 'Intermediate',
  },

  // --- Core / Arm Balances (코어 / 암 밸런스) ---
  {
    name: '플랭크 자세 (쿰바카아사나)',
    sanskritName: 'Kumbhakasana',
    description: '코어, 어깨, 팔, 다리의 근력을 키우는 기초적이면서도 중요한 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 18H2M6 8l10-4 4 4M6 8L2 18m18 0l-4-10"/></svg>`,
    benefits: ["팔, 손목, 척추 강화", "복부 탄력 증가", "암 밸런스 동작을 위한 기초 체력 향상"],
    contraindications: ["손목터널증후군"],
    difficulty: 'Beginner',
  },
  {
    name: '차투랑가 단다아사나',
    sanskritName: 'Chaturanga Dandasana',
    description: '태양 경배 자세의 일부로, 팔, 어깨, 다리의 힘을 기르는 전신 근력 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12h16m-14 4h12M6 8h12"/></svg>`,
    benefits: ["팔, 손목, 어깨 강화", "복부 탄력 증가", "암 밸런스 준비"],
    contraindications: ["손목터널증후군", "어깨, 팔꿈치, 손목 부상", "임신"],
    difficulty: 'Intermediate',
  },
  {
    name: '까마귀 자세 (바카아사나)',
    sanskritName: 'Bakasana',
    description: '팔과 복부의 힘으로 몸을 띄우는 암 밸런스 동작으로 집중력을 요합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a4 4 0 00-4 4c0 2.21 1.79 4 4 4s4-1.79 4-4a4 4 0 00-4-4zm-4 8h8l-2 6h-4l-2-6zM5 22h14"/></svg>`,
    benefits: ["팔과 손목 강화", "등 상부 스트레칭", "균형 감각 및 코어 강화"],
    contraindications: ["임신", "손목터널증후군", "손목/어깨 부상"],
    difficulty: 'Advanced',
  },
  {
    name: '사이드 플랭크 (바시스타아사나)',
    sanskritName: 'Vasisthasana',
    description: '한 팔로 균형을 잡으며 손목, 팔, 어깨를 강화하고 코어를 단련하는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 22l10-20 10 20z"/></svg>`,
    benefits: ["팔, 배, 다리 강화", "손목 스트레칭 및 강화", "균형 감각 향상"],
    contraindications: ["손목, 팔꿈치, 어깨 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '반딧불이 자세 (티티바아사나)',
    sanskritName: 'Tittibhasana',
    description: '햄스트링의 유연성과 강력한 코어 및 팔 근력이 필요한 고급 암 밸런스입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l3 5h6l-3 5 2 5-6-3-6 3 2-5-3-5h6z"/></svg>`,
    benefits: ["서혜부 안쪽과 등 스트레칭", "팔과 손목 강화", "복부 탄력 증가"],
    contraindications: ["어깨, 팔꿈치, 손목, 허리 부상"],
    difficulty: 'Advanced',
  },
  {
    name: '8각 자세 (아스타바크라아사나)',
    sanskritName: 'Astavakrasana',
    description: '몸을 비대칭으로 꼬아 팔로 지탱하는 동작으로 코어 힘과 균형이 필요합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>`,
    benefits: ["손목과 팔 강화", "복부 근육 단련", "소화 기능 개선"],
    contraindications: ["손목, 팔꿈치, 어깨 부상"],
    difficulty: 'Advanced',
  },
  {
    name: '공작 자세 (마유라아사나)',
    sanskritName: 'Mayurasana',
    description: '팔꿈치로 복부를 받치고 몸을 수평으로 띄우는 고난이도 암 밸런스입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l2 4h5l-4 4 1 5-4-3-4 3 1-5-4-4h5z"/></svg>`,
    benefits: ["손목과 전완근 강화", "복부 탄력 증가", "소화 기능 개선"],
    contraindications: ["손목/팔꿈치 부상", "심장 질환", "임신"],
    difficulty: 'Advanced',
  },
  {
    name: '저울 자세 (톨라아사나)',
    sanskritName: 'Tolasana',
    description: '연꽃 자세에서 손으로 바닥을 밀어 몸을 들어 올리는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    benefits: ["손목, 팔, 복부 강화", "복부 근육 단련"],
    contraindications: ["어깨 또는 손목 부상"],
    difficulty: 'Advanced',
  },

  // --- Inversions (역자세) ---
  {
    name: '어깨 서기 (살람바 사르방가아사나)',
    sanskritName: 'Salamba Sarvangasana',
    description: '전신의 혈액순환을 돕고 뇌를 진정시키는 요가의 여왕이라 불리는 자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M5 12h14"/></svg>`,
    benefits: ["뇌 진정 및 스트레스 해소", "갑상선 및 전립선 자극", "어깨와 목 스트레칭"],
    contraindications: ["설사", "두통", "고혈압", "생리 중", "목 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '쟁기 자세 (할라아사나)',
    sanskritName: 'Halasana',
    description: '다리를 머리 뒤로 넘겨 등과 목을 깊게 스트레칭하고 수면을 돕는 자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22h14a2 2 0 0 0 2-2V7.5L12 2 4 7.5V20a2 2 0 0 0 2 2z"/><path d="M12 22v-6.5"/><path d="M12 11.5V6.5"/></svg>`,
    benefits: ["뇌 진정", "복부 장기 및 갑상선 자극", "어깨와 척추 스트레칭"],
    contraindications: ["설사", "생리 중", "목 부상", "천식", "임신"],
    difficulty: 'Intermediate',
  },
  {
    name: '귀를 막는 자세 (카르나피다아사나)',
    sanskritName: 'Karnapidasana',
    description: '쟁기 자세에서 무릎을 굽혀 귀 옆으로 가져오는 심화 동작으로, 외부 감각을 차단하고 내면에 집중하게 합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zM4 20h16v-2c0-2.66-5.33-4-8-4s-8 1.34-8 4v2z"/></svg>`,
    benefits: ["척추와 어깨 깊은 스트레칭", "복부 장기 자극", "마음의 안정 및 감각 제어(프라치아하라)"],
    contraindications: ["목 부상", "고혈압", "생리 중", "임신"],
    difficulty: 'Advanced',
  },
  {
    name: '물고기 자세 (마츠야아사나)',
    sanskritName: 'Matsyasana',
    description: '어깨 서기의 반대 자세로, 목구멍, 가슴, 복부를 시원하게 열어줍니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s5-7 10-7 10 7 10 7-5 7-10 7-10-7-10-7z"/><circle cx="12" cy="12" r="3"/></svg>`,
    benefits: ["고관절 굴곡근과 늑간근 스트레칭", "복부와 목 앞쪽 자극", "등 상부 강화"],
    contraindications: ["고혈압/저혈압", "편두통", "불면증", "허리 또는 목 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '머리 서기 (시르사아사나)',
    sanskritName: 'Sirsasana',
    description: '요가 자세의 왕이라 불리며, 전신의 근력과 집중력을 기르는 역자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="7" r="4"/><path d="M5.5 21h13M12 21v-7"/><path d="M12 11l-3 3 3 3 3-3-3-3z"/></svg>`,
    benefits: ["뇌 진정 및 스트레스 완화", "팔, 다리, 척추 강화", "복부 장기 탄력 증가"],
    contraindications: ["허리 부상", "두통", "심장 질환", "고혈압", "생리 중", "목 부상"],
    difficulty: 'Advanced',
  },
  {
    name: '전갈 자세 (브르스치카아사나)',
    sanskritName: 'Vrischikasana',
    description: '전갈의 모습을 닮은 고난이도 역자세이자 후굴 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l3 6-3 6-3-6 3-6z"/><path d="M12 22V14"/></svg>`,
    benefits: ["몸통과 등 강화", "균형 감각 향상", "가슴과 어깨 유연성 증대"],
    contraindications: ["등, 어깨, 목 부상", "심장 문제", "고혈압"],
    difficulty: 'Advanced',
  },
  {
    name: '물구나무 서기 (아도 무카 브릭샤아사나)',
    sanskritName: 'Adho Mukha Vrksasana',
    description: '핸드스탠드라고도 불리며, 전신의 힘과 균형, 집중력이 요구되는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="19" x2="12" y2="5"/><polyline points="5 12 12 5 19 12"/></svg>`,
    benefits: ["어깨, 팔, 손목 강화", "복부 스트레칭", "균형 감각 향상"],
    contraindications: ["등, 어깨, 목 부상", "두통", "심장 질환", "고혈압"],
    difficulty: 'Advanced',
  },

  // --- Hip Openers & Others (골반 & 기타) ---
  {
    name: '비둘기 자세 (에카 파다 라자카포타아사나)',
    sanskritName: 'Eka Pada Rajakapotasana',
    description: '허벅지, 서혜부, 장요근을 깊게 스트레칭하는 강력한 골반 오픈 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 11-5.93-9.14"/><path d="M22 4L12 14.01l-3-3"/></svg>`,
    benefits: ["고관절 굴곡근 개방", "허벅지와 둔근 스트레칭", "좌골 신경통 완화"],
    contraindications: ["무릎 부상", "천장관절 문제", "발목 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '도마뱀 자세 (우탄 프리스타아사나)',
    sanskritName: 'Utthan Pristhasana',
    description: '햄스트링, 고관절 굴곡근, 서혜부를 깊게 열어주는 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5v14M5 12h14"/></svg>`,
    benefits: ["골반, 햄스트링, 서혜부 개방", "허벅지 안쪽 근육 스트레칭", "깊은 골반 동작 준비"],
    contraindications: ["무릎 또는 엉덩이 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '와일드 씽 (카마트카라아사나)',
    sanskritName: 'Camatkarasana',
    description: '가슴, 폐, 어깨 부위를 시원하게 여는 역동적이고 즐거운 후굴 동작입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M10 9l-6 6 6 6"/><path d="M20 4v16"/></svg>`,
    benefits: ["가슴, 폐, 어깨 부위 개방", "고관절 굴곡근 스트레칭", "어깨와 등 상부 근력 강화"],
    contraindications: ["손목터널증후군", "회전근개 부상"],
    difficulty: 'Intermediate',
  },
  {
    name: '화환 자세 (말라아사나)',
    sanskritName: 'Malasana',
    description: '골반과 서혜부를 열고 발목과 허리를 스트레칭하는 쪼그려 앉는 자세입니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a9 9 0 1 0 9 9 9 9 0 0 0-9-9z"/><path d="M8 14s2 2 4 2 4-2 4-2"/></svg>`,
    benefits: ["발목, 서혜부, 등 스트레칭", "복부 탄력 증가", "배설 기능 돕기"],
    contraindications: ["무릎 또는 허리 부상"],
    difficulty: 'Beginner',
  },
  {
    name: '원숭이 자세 (하누만아사나)',
    sanskritName: 'Hanumanasana',
    description: '원숭이 신 하누만의 도약을 형상화한 동작으로, 흔히 다리 찢기라고 불리며 극도의 유연성을 요합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="20" x2="20" y2="4"/><line x1="20" y1="20" x2="4" y2="4"/></svg>`,
    benefits: ["허벅지, 햄스트링, 서혜부 스트레칭", "복부 장기 자극"],
    contraindications: ["햄스트링 또는 서혜부 부상"],
    difficulty: 'Advanced',
  },
  {
    name: '송장 자세 (사바아사나)',
    sanskritName: 'Savasana',
    description: '완전한 이완을 위한 자세로, 보통 수련의 마지막에 행합니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12h16M9 16h6M9 8h6"/></svg>`,
    benefits: ["뇌 진정 및 스트레스 해소", "신체 이완", "두통, 피로, 불면증 완화"],
    contraindications: ["허리 부상 (무릎을 굽히고 수행)"],
    difficulty: 'Beginner',
  },
  {
    name: '강아지 자세 (우타나 시소아사나)',
    sanskritName: 'Uttana Shishosana',
    description: '아기 자세와 견상 자세의 중간 형태로, 척추와 어깨를 부드럽게 늘려줍니다.',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 16v-4a4 4 0 0 0-8 0v4"/><circle cx="12" cy="12" r="9"/></svg>`,
    benefits: ["척추와 어깨 스트레칭", "마음의 안정"],
    contraindications: ["무릎 부상"],
    difficulty: 'Beginner',
  }
];
